#macro IDLING 0
#macro WALKING 1
#macro SLOWING 2
#macro JUMPING 3
#macro FLYING 4
#macro DYING 5
#macro DAMAGED 6
#macro STUNNED 7
#macro FROZEN 8
#macro ABILITY_FORWARD 9
#macro ABILITY_RADIAL 10
#macro ABILITY_UP 11
#macro ABILITY_DOWN 12

#macro PRIMARY 0
#macro SECONDARY 1
#macro UTILITY 2
#macro ULTIMATE 3
#macro PASSIVE 4